spring:
  application:
    name: codebrainer-orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5432/codebrainer
    username: codebrainer
    password: codebrainer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host:  rabbitmq
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

storage:
  base-path: ./storage

judge0:
  api-url: http://localhost:2358
  callback-url: http://localhost:8080/internal/judge0/callback
  callback-enabled: false

queue:
  submission:
    name: submissions.queue
    routing-key: submissions.key
    exchange: submissions.exchange

codebrainer:
  submission:
    poll-delay-ms: 1000
    max-poll-attempts: 30

