spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codebrainer
    username: codebrainer
    password: codebrainer
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: false

storage:
  base-path: ./storage

judge0:
  api-url: http://54.252.182.149:2358

